### ISSUE TITLE
How does this work?

### ISSUE THREAD

**Issue by parro-it** [TremayneChrist/ProtectJS#9]
I did a look at the source code, I don't understand how this library could possibly work...

If I'm not wrong, a public function of a protected object is allowed to call private methods of any other protected objects, because `callDepth` is shared between all objects. 

Am I missing something?

**Comment by TremayneChrist** [comment]
Hey @parro-it,

The objects own public methods are allowed to call private ones, however, any that are added after the object has been protected will be blocked. `callDepth` is shared, but the function calls will always be synchronous so this doesn't matter.

**Comment by TremayneChrist** [comment]
Ah I see what you mean now. Yeah, good spot! I've moved the scope of the call depth in #11
